name: 'Pull Request another repository'
description: 'Used for pull request a copy of a folder to another repository'
inputs:
  source_folder:
    description: 'Source folder from origin'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_folder:
    description: 'Destination folder to push the origin folder'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_head_branch:
    description: 'The branch to create to push the changes. Cannot be master or main'
    required: true
  pr_title:
    description: 'The PR title which will be defined in the PR'
    required: true
  commit_msg:
    description: 'The commit message which will be used.'
    required: true
  destination_base_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: "main"
  pull_request_reviewers:
    description: 'Pull request reviewers users'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-folder }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.destination-head-branch }}
    - ${{ inputs.destination-base-branch }}
    - ${{ inputs.pull-request-reviewers }}
    - ${{ inputs.commit_msg }}
    - ${{ inputs.pr_title }}
branding:
  icon: 'git-commit'
  color: 'green'
